language: rust
rust:
  # - stable
  # - beta
  - nightly
sudo: false
cache: cargo
branches:
  only:
    - master
script:
  - cargo test
  - cargo test --examples
  - cargo run --example gaussian_mom
  - cargo run --example category_mom
  - cargo run --example spam
notifications:
  email:
    on_success: never