language: rust
rust:
  # - stable
  # - beta
  - nightly
sudo: false
cache: cargo
branches:
  only:
    - master
script:
  - cargo test
  - cargo test --examples
notifications:
  email:
    on_success: never