[package]
name = "rust_nb"
version = "0.1.0"
authors = ["Fuyang Liu <liufuyang@users.noreply.github.com>"]
edition = "2018"

[dependencies]
regex = "1"
rayon = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"